---
title       : Comparison of Automated Gating and Centralized Manual Gating
subtitle    : FOCIS 2013, Cytome Meeting
author      : Ryan Brinkman, Greg Finak and the FlowCAP Committee
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
---

## T-helper Panel
  
```{r load,echo=FALSE}
load("../../data/MergedTables.rda")
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(slidify))


```
```{r boxplots.thelper,echo=FALSE,warning=FALSE,message=FALSE,error=FALSE,fig.width=14.5,cache=TRUE}
ggplot(subset(THELPER,!Population%in%c("CD4","CD8","Lymphocytes")))+geom_boxplot(aes(y=Proportion,x=Center,fill=Method))+facet_wrap(~Population,scales="free_y")+scale_x_discrete(name="Center",labels=LETTERS[1:7])

```

---

## B-cell Panel

```{r boxplots.bcell,echo=FALSE,warning=FALSE,message=FALSE,error=FALSE,fig.width=14.5,cache=TRUE}
ggplot(subset(BCELL,!Population%in%"Lymphocytes"))+geom_boxplot(aes(y=Proportion,x=Center,fill=Method))+facet_wrap(~Population,scales="free_y")+scale_x_discrete(name="Center",labels=LETTERS[1:7])

```


---

## T-cell Panel

```{r boxplots.tcelll,echo=FALSE,warning=FALSE,message=FALSE,error=FALSE,fig.width=14.5,cache=TRUE}
ggplot(subset(TCELLS,!Sample%in%c("1349")&!Population%in%"Lymphocytes"))+geom_boxplot(aes(y=Proportion,x=Center,fill=Method))+facet_wrap(~Population,scales="free_y")+scale_x_discrete(name="Center",labels=LETTERS[1:7])

```


---


## T-reg Panel

```{r boxplots.treg,echo=FALSE,warning=FALSE,message=FALSE,error=FALSE,fig.width=14.5,cache=TRUE}
ggplot(subset(TREG,!Population%in%"Lymphocytes"))+geom_boxplot(aes(y=Proportion,x=Center,fill=Method))+facet_wrap(~Population,scales="free_y")+scale_x_discrete(name="Center",labels=LETTERS[1:7])

```

---
  
## Coefficient of Variation for T-cells

```{r cv.tcell,echo=FALSE,message=FALSE,warning=FALSE,error=FALSE,fig.width=14.5}

ggplot(ddply(TCELLS,.(Center,Population,Method),summarize,CV=sd(Proportion,na.rm=TRUE)/mean(Proportion,na.rm=TRUE)))+geom_point(aes(x=Center,y=CV*100,color=Method,shape=Method),alpha=0.8,size=4)+facet_wrap(~Population)+scale_x_discrete(name="Center",labels=LETTERS[1:7])

```

---
  
## Coefficient of Variation for T-helper

```{r cv.thelper,echo=FALSE,message=FALSE,warning=FALSE,error=FALSE,fig.width=14.5}

ggplot(ddply(THELPER,.(Center,Population,Method),summarize,CV=sd(Proportion,na.rm=TRUE)/mean(Proportion,na.rm=TRUE)))+geom_point(aes(x=Center,y=CV*100,color=Method,shape=Method),alpha=0.8,size=4)+facet_wrap(~Population)+scale_x_discrete(name="Center",labels=LETTERS[1:7])

```

---
  
## Coefficient of Variation for T-regulatory

```{r cv.treg,echo=FALSE,message=FALSE,warning=FALSE,error=FALSE,fig.width=14.5}

ggplot(ddply(TREG,.(Center,Population,Method),summarize,CV=sd(Proportion,na.rm=TRUE)/mean(Proportion,na.rm=TRUE)))+geom_point(aes(x=Center,y=CV*100,color=Method,shape=Method),alpha=0.8,size=4)+facet_wrap(~Population)+scale_x_discrete(name="Center",labels=LETTERS[1:7])

```

---
  
## Coefficient of Variation for B-cells

```{r cv.bcell,echo=FALSE,message=FALSE,warning=FALSE,error=FALSE,fig.width=14.5}

ggplot(ddply(BCELL,.(Center,Population,Method),summarize,CV=sd(Proportion,na.rm=TRUE)/mean(Proportion,na.rm=TRUE)))+geom_point(aes(x=Center,y=CV*100,color=Method,shape=Method),alpha=0.8,size=4)+facet_wrap(~Population)+scale_x_discrete(name="Center",labels=LETTERS[1:7])

```

----

## Bias for Bcells


```{r bias.bcell,echo=FALSE,message=FALSE,warning=FALSE,error=FALSE,fig.width=14.5,cache=FALSE}
bias<-function(FOO){
  FOO <- data.table(FOO)
  setkey(FOO,"Center","File","Population")
A <-  FOO[,{
    E <- data.frame(E=(.SD$Proportion-.SD[Method=="Manual",,]$Proportion)/(.SD[Method=="Manual",,]$Proportion));
    mth <- data.frame(Method=.SD$Method)
    if(nrow(E)!=nrow(mth)){
      ret <- data.frame(Method=mth,E=NA_real_)
    }else{
      ret <- cbind(Method=mth,E)
    }
    ret
  },c("Center","File","Population")]
A <- ddply(subset(A,!Population%in%"Lymphocytes"),.(Center,Population,Method),summarize,SPE=mean(abs(E)))
A
}

A<-bias(BCELL)
ggplot(A)+geom_point(aes(x=Center,y=100*SPE,color=Method),alpha=0.8,size=4)+facet_wrap(~Population,scales="free_y")+scale_x_discrete(name="Center",labels=LETTERS[1:7])+scale_y_continuous(name="% Error")
```
---

## Bias for T-cells
```{r bias.tcell,echo=FALSE,message=FALSE,warning=FALSE,error=FALSE,fig.width=14.5,cache=FALSE}
B<-bias(TCELLS)
ggplot(B)+geom_point(aes(x=Center,y=100*SPE,color=Method),alpha=0.8,size=4)+facet_wrap(~Population,scales="free_y")+scale_x_discrete(name="Center",labels=LETTERS[1:7])+scale_y_continuous(name="% Error")
```
---

## Bias for T-regs
```{r bias.treg,echo=FALSE,message=FALSE,warning=FALSE,error=FALSE,fig.width=14.5,cache=FALSE}
  C<-bias(TREG)
ggplot(C)+geom_point(aes(x=Center,y=100*SPE,color=Method),alpha=0.8,size=4)+facet_wrap(~Population,scales="free_y")+scale_x_discrete(name="Center",labels=LETTERS[1:7])+scale_y_continuous(name="% Error")
```
---

## Bias for T-helpers
```{r bias.thelp,echo=FALSE,message=FALSE,warning=FALSE,error=FALSE,fig.width=14.5,cache=FALSE}
  D<-bias(THELPER)
ggplot(D)+geom_point(aes(x=Center,y=100*SPE,color=Method),alpha=0.8,size=4)+facet_wrap(~Population,scales="free_y")+scale_x_discrete(name="Center",labels=LETTERS[1:7])+scale_y_continuous(name="% Error")
  
```
